#!/usr/bin/env python3
# Copyright 2026 Philterd, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Regenerates ``tokenizer_parity.json`` -- the golden SentencePiece token ids that
``GlinerTokenizerParityTests`` asserts the .NET ``SentencePieceTokenizer`` reproduces
token-for-token.

The reference is the Python ``sentencepiece`` library loading the very same
``spm.model`` the .NET path loads (deberta-v3's SentencePiece model, as shipped in
``philterd/ph-eye-pii-base``). ``Microsoft.ML.Tokenizers.SentencePieceTokenizer`` is a
faithful port of this library, so for ordinary text the two produce identical ids
(NFKC normalization, the leading-space ``_`` marker, sub-word merges, and all). This
script needs only ``spm.model`` -- no ONNX graph, no transformers, no network.

The GLiNER sentinels ``<<ENT>>`` / ``<<SEP>>`` are NOT part of the SentencePiece
vocabulary; the .NET pipeline registers them as specials and frames them around the
encoded pieces by hand (see ``GlinerModel``). They therefore never arise from encoding
ordinary text and are covered separately by a dedicated assertion in the test, not by
this fixture.

Usage:
    pip install sentencepiece
    python generate_tokenizer_fixture.py [path/to/spm.model]

With no argument it uses the committed ``spm.model`` sitting next to this script.
Re-run it whenever the inputs below or the underlying ``spm.model`` change, then commit
the regenerated ``tokenizer_parity.json``.

No real data appears in any input -- every string is synthetic.
"""

import json
import os
import sys

import sentencepiece as spm

# Each input is tagged with the GLiNER-pipeline case class it exercises. The classes the
# issue calls out -- multi-subword words, hyphenated runs (SSNs, dates), and email-style
# punctuation splits -- are all represented, alongside names, identifiers, phone numbers,
# Unicode normalization, and the bare label fragments used as the detection prompt.
INPUTS = [
    # Names and intra-word punctuation.
    "John Q. Public",
    "O'Brien-Smith",
    # Hyphenated runs: dates and SSNs stay single "words" in the pipeline's word split.
    "Patient was seen on 2024-03-02.",
    "SSN 123-45-6789",
    "DOB 1985-07-04",
    # Multi-subword words (clinical vocabulary the base SentencePiece model fragments).
    "Hemoglobin A1c was 7.2% on 2023-11-15.",
    "Acetaminophen administered intravenously.",
    # Email-style punctuation splits.
    "j.public@example.com",
    "jane_doe-01@test-domain.co.uk",
    # Identifiers and phone numbers.
    "MRN: AB-1234567",
    "(555) 123-4567",
    # Unicode normalization: accents, fullwidth forms, and ligatures must fold identically.
    "café naïve résumé Zürich",
    "Ｆｕｌｌｗｉｄｔｈ　１２３",
    "ﬁle ﬂag",
    # A plain sentence as a baseline.
    "The quick brown fox jumps over the lazy dog.",
    # Bare label fragments -- the strings the GLiNER prompt encodes for each entity type.
    "person",
    "email address",
    "social security number",
    "date",
    "phone number",
    # Post-split word fragments: the GLiNER pipeline runs SplitWords first and encodes each
    # resulting word on its own, so an email is fed as these standalone pieces, never whole.
    # These mirror encode(word.Text) exactly -- the leading-space behavior on a standalone
    # fragment is what the pipeline actually depends on.
    "j",
    ".",
    "public",
    "@",
    "example",
    "com",
    "Hemoglobin",
    "A1c",
    "2024-03-02",
    "123-45-6789",
]


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    spm_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "spm.model")

    sp = spm.SentencePieceProcessor()
    sp.Load(spm_path)

    cases = [{"input": text, "ids": sp.EncodeAsIds(text)} for text in INPUTS]
    fixture = {
        "_note": (
            "Golden deberta-v3 SentencePiece token ids generated by "
            "generate_tokenizer_fixture.py from spm.model using the Python sentencepiece "
            "library. Asserted token-for-token against the .NET SentencePieceTokenizer by "
            "GlinerTokenizerParityTests. No real data; all inputs are synthetic."
        ),
        "cases": cases,
    }

    out_path = os.path.join(here, "tokenizer_parity.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(fixture, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Wrote {len(cases)} cases to {out_path}")


if __name__ == "__main__":
    main()
