<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Phileas.Policy</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Phileas.Model/Phileas.Model.csproj" />
  </ItemGroup>
</Project>
